name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.0=py313hfc0e8ea_101
  - annotated-types=0.6.0=py313h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - bat=0.26.1=hdab8a38_0
  - binutils=2.40=h4852527_7
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40=hb3c18ed_9
  - black=25.1.0=pyh866005b_0
  - boltons=24.1.0=py313h06a4308_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - c-compiler=1.11.0=h4d9bdce_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.3.1=pyh8f84b5b_1
  - cmake=3.31.1=hf9cb763_0
  - compilers=1.11.0=ha770c72_0
  - conda=25.11.1=py313h78bf25f_0
  - conda-anaconda-telemetry=0.1.2=py313h06a4308_1
  - conda-anaconda-tos=0.1.3=py313h06a4308_0
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-gcc-specs=14.3.0=he8ccf15_15
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313h06a4308_0
  - conda-package-streaming=0.11.0=py313h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cppcheck=2.18.3=py313h7566ad9_1
  - cryptography=44.0.1=py313h7825ff9_0
  - cxx-compiler=1.11.0=hfcd1e18_0
  - distro=1.9.0=py313h06a4308_0
  - eslint=9.39.1=h4fc9b5d_1
  - eslint-plugin-react=7.36.1=h5ac6406_1
  - expat=2.7.3=hecca717_0
  - fd-find=10.3.0=hdab8a38_0
  - fmt=9.1.0=hdb19cb5_1
  - fortls=3.2.2=py313h78bf25f_1
  - fortran-compiler=1.11.0=h9bea470_0
  - frozendict=2.4.2=py313h06a4308_0
  - fzf=0.67.0=h6138981_0
  - gcc=14.3.0=h76bdaa0_7
  - gcc_impl_linux-64=14.3.0=hd9e9e21_7
  - gcc_linux-64=14.3.0=h298d278_14
  - gfortran=14.3.0=he448592_7
  - gfortran_impl_linux-64=14.3.0=h1a219da_15
  - gfortran_linux-64=14.3.0=h1e4d427_14
  - git=2.52.0=pl5321h6d3cee1_1
  - gxx=14.3.0=he448592_7
  - gxx_impl_linux-64=14.3.0=he663afc_7
  - gxx_linux-64=14.3.0=hcfe7c2f_14
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - isort=7.0.0=pyhd8ed1ab_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - kernel-headers_linux-64=4.18.0=he073ed8_8
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lfortran=0.58.0=h2f44d25_0
  - libarchive=3.7.7=hadbb8c3_0
  - libcurl=8.17.0=h4e3cde8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=he0feb66_15
  - libgcc-devel_linux-64=14.3.0=h85bb3a7_107
  - libgcc-ng=15.2.0=h69a702a_15
  - libgfortran5=15.2.0=h68bc16d_15
  - libgomp=15.2.0=he0feb66_15
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libmamba=2.0.5=haf1ee3a_1
  - libmambapy=2.0.5=py313hdb19cb5_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.0=had1ee68_0
  - libsanitizer=14.3.0=hd08acf3_7
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.35=h9463b59_0
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-devel_linux-64=14.3.0=h85bb3a7_107
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libtree-sitter=0.25.9=h280c20c_0
  - libunistring=0.9.10=h7f98852_0
  - libunwind=1.7.2=he02047a_0
  - libutf8proc=2.11.2=hfe17d71_0
  - libuuid=2.41.2=h5347b49_1
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lua-language-server=3.14.0=h3f2d84a_1
  - lua-lpeg=1.1.0=h73b1eb8_4
  - luajit-openresty=2.1_20251030=h280c20c_1
  - luv=1.51.0=h73b1eb8_1
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h280c20c_1002
  - markdown-it-py=2.2.0=py313h06a4308_1
  - mdurl=0.1.0=py313h06a4308_0
  - menuinst=2.2.0=py313h06a4308_1
  - mypy=1.19.1=py313h07c4f96_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.11.3=he02047a_1
  - nodejs=24.10.0=h4d2b252_0
  - nvim=0.11.5=h6367a8b_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=24.2=py313h06a4308_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.47=haa7fec5_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=25.0=py313h06a4308_0
  - platformdirs=4.3.7=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - prettier=3.7.4=h7e4c9f4_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py313h06a4308_0
  - pydantic-core=2.27.1=py313h4aa5aa6_0
  - pygments=2.19.1=py313h06a4308_0
  - pyrefly=0.44.2=h2b88eb6_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.0=h9ebbce0_101_cp313
  - python-librt=0.7.7=py313h54dd161_0
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py313h06a4308_1
  - rhash=1.4.6=hb9d3cd8_1
  - rich=13.9.4=py313h06a4308_0
  - ripgrep=15.1.0=hdab8a38_0
  - ruamel.yaml=0.18.10=py313h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - ruff=0.14.11=h4196e79_0
  - rust=1.89.0=hd1a145a_0
  - rust-src=1.89.0=unix_0
  - setuptools=78.1.1=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - spdlog=1.11.0=hdb19cb5_0
  - sqlite=3.51.1=hbc0de68_0
  - stylua=2.3.1=hb17b654_1
  - sysroot_linux-64=2.28=h4ee821c_8
  - tinyxml2=11.0.0=h3f2d84a_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.1=py313h7040dfc_0
  - truststore=0.10.0=py313h06a4308_0
  - typescript=5.7.3=h80e38bb_0
  - typescript-eslint-eslint-plugin=8.48.1=hcdd682b_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - unibilium=2.1.2=h280c20c_1
  - urllib3=2.3.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xeus=5.1.1=h4795217_0
  - xeus-zmq=3.0.0=h130ccd7_1
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - yazi=26.1.4=hdab8a38_0
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py313h54dd161_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.2.2
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - comm==0.2.2
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fqdn==1.5.1
      - fsspec==2025.3.2
      - h11==0.16.0
      - h5py==3.13.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipykernel==6.29.5
      - ipython==9.2.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - keras==3.9.2
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - namex==0.0.9
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.4.2
      - notebook-shim==0.2.4
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - optree==0.15.0
      - overrides==7.7.0
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydot==4.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.24.0
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.14.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.7.0
      - tornado==6.4.2
      - traitlets==5.14.3
      - triton==3.3.0
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
prefix: /home/ans18010/miniconda3
